-- Create the calculator_history table
CREATE TABLE public.calculator_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  expression TEXT,
  result TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Add index on user_id and created_at for faster history lookups
CREATE INDEX idx_calculator_history_user_created ON public.calculator_history (user_id, created_at DESC);

-- Enable Row Level Security
ALTER TABLE public.calculator_history ENABLE ROW LEVEL SECURITY;

-- Policy: Allow users to insert their own history
CREATE POLICY "Allow users to insert their own calculator history" 
ON public.calculator_history
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Policy: Allow users to select their own history
CREATE POLICY "Allow users to select their own calculator history" 
ON public.calculator_history
FOR SELECT USING (auth.uid() = user_id);

-- Policy: Allow users to delete their own history
CREATE POLICY "Allow users to delete their own calculator history" 
ON public.calculator_history
FOR DELETE USING (auth.uid() = user_id);

-- Grant usage permission for the public schema (if not already granted)
GRANT USAGE ON SCHEMA public TO service_role;

-- Grant specific permissions on the table to authenticated users
GRANT SELECT, INSERT, DELETE ON TABLE public.calculator_history TO authenticated;
